CREATE TABLE APP_USER (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    BALANCE DECIMAL(10,2) NOT NULL
);
INSERT INTO APP_USER ( NAME, BALANCE) VALUES ( 'Ibrahima', 1000.0);
INSERT INTO APP_USER ( NAME, BALANCE) VALUES ( 'Saikou', 500.0);
INSERT INTO APP_USER ( NAME, BALANCE) VALUES ( 'Mamadou', 50000.0);
INSERT INTO APP_USER ( NAME, BALANCE) VALUES ( 'Abdoul', 50000.0);